version: '3.9'
# Web frontend compose configuration.
services:
  ssb_webapp:
    build:
      context: ${APP_DIR}
      dockerfile: src/webapp/Dockerfile
    container_name: ssb_webapp
    ports:
      - "7979:7979"
    command: ["uvicorn", "src.webapp.webapp:app", "--host", "0.0.0.0", "--port", "7979", "--reload", "--reload-dir", "/app/src/webapp"]
    env_file:
      - .env
    volumes:
      - ${DATA_DIR}:/app/data
      - ${APP_DIR}:/app
    restart: unless-stopped
