version: '3.9'
# Web frontend compose configuration.
services:
  ssb_webapp:
    build:
      context: ../..
      dockerfile: src/webapp/Dockerfile
    container_name: ssb_webapp
    ports:
      - "7878:7878"
    command: ["uvicorn", "src.webapp.webapp:app", "--host", "0.0.0.0", "--port", "7878", "--reload", "--reload-dir", "/app/src/webapp"]
    env_file:
      - .env
    volumes:
      - ${DATA_DIR}:/app/data
      - ${APP_DIR}:/app
    restart: unless-stopped
