version: "3.9"
services:
  ssb-retuning-automations:
    image: jaimetur/ssb-retuning-automations:${IMAGE_TAG}
    container_name: ssb-retuning-automations
    ports:
      - "7878:7878"
    volumes:
      - ${DATA_DIR}:/app/data
    restart: unless-stopped
